apiVersion: v1
kind: Service
metadata:
  name: bankgateway
  labels:
    app: bankgateway
    service: bankgateway
spec:
  type: LoadBalancer
  ports:
    - port: 8765
      targetPort: 8765
      protocol: TCP
  selector:
    service: bankgateway